<?php

return [
    'info' => [
        'opcode' => 0x1F43,
        'destination' => 'gdeliveryd'
    ],
    'retcode' => 'int',
    'GRoleData' => [
        'base' => [
            'version' => 'byte',
            'id' => 'int',
            'name' => 'name',
            'race' => 'int',
            'cls' => 'int',
            'gender' => 'byte',
            'custom_data' => 'octets',
            'config_data' => 'octets',
            'custom_stamp' => 'int',
            'status' => 'byte',
            'delete_time' => 'int',
            'create_time' => 'int',
            'lastlogin_time' => 'int',
            'forbidcount' => 'cuint',
            'forbid' => [
                'type' => 'byte',
                'time' => 'int',
                'createtime' => 'int',
                'reason' => 'name',
            ],
            'help_states' => 'octets',
            'spouse' => 'int',
            'userid' => 'int',
            'cross_data' => 'octets',
            'reserved2' => 'byte',
            'reserved3' => 'byte',
            'reserved4' => 'byte',
        ],
        'status' => [
            'sversion' => 'byte',
            'level' => 'int',
            'level2' => 'int',
            'exp' => 'int',
            'sp' => 'int',
            'pp' => 'int',
            'hp' => 'int',
            'mp' => 'int',
            'posx' => 'float',
            'posy' => 'float',
            'posz' => 'float',
            'worldtag' => 'int',
            'invader_state' => 'int',
            'invader_time' => 'int',
            'pariah_time' => 'int',
            'reputation' => 'int',
            'custom_status' => 'octets',
            'filter_data' => 'octets',
            'charactermode' => 'octets',
            'instancekeylist' => 'octets',
            'dbltime_expire' => 'int',
            'dbltime_mode' => 'int',
            'dbltime_begin' => 'int',
            'dbltime_used' => 'int',
            'dbltime_max' => 'int',
            'time_used' => 'int',
            'dbltime_data' => 'octets',
            'storesize' => 'short',
            'petcorral' => 'octets',
            'property' => 'octets',
            'var_data' => 'octets',
            'skills' => 'octets',
            'storehousepasswd' => 'octets',
            'waypointlist' => 'octets',
            'coolingtime' => 'octets',
            'npc_relation' => 'octets',
            'multi_exp_ctrl' => 'octets',
            'storage_task' => 'octets',
            'faction_contrib' => 'octets',
            'force_data' => 'octets',
            'online_award' => 'octets',
            'profit_time_data' => 'octets',
            'country_data' => 'octets',
            'king_data' => 'octets',
            'meridian_data' => 'octets',
            'extraprop' => 'octets',
            'title_data' => 'octets',
            'reincarnation_data' => 'octets',
            'realm_data' => 'octets',
            'reserved2' => 'byte',
            'reserved3' => 'byte',
        ],
        'pocket' => [
            'icapacity' => 'int',
            'timestamp' => 'int',
            'money' => 'int',
            'invcount' => 'cuint',
            'inv' => [
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int',
            ],
            'reserved6' => 'int',
            'reserved7' => 'int',
        ],
        'equipment' => [
            'eqpcount' => 'cuint',
            'eqp' => [
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int',
            ],
        ],
        'storehouse' => [
            'capacity' => 'int',
            'money' => 'int',
            'storecount' => 'cuint',
            'store' => [
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int',
            ],
            'size1' => 'byte',
            'size2' => 'byte',
            'dresscount' => 'cuint',
            'dress' => [
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int',
            ],
            'materialcount' => 'cuint',
            'material' => [
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int',
            ],
            'size3' => 'byte',
            'generalcardcount' => 'cuint',
            'generalcard' => [
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int',
            ],
            'reserved' => 'short',
        ],
        'task' => [
            'task_data' => 'octets',
            'task_complete' => 'octets',
            'task_finishtime' => 'octets',
            'task_inventorycount' => 'cuint',
            'task_inventory' => [
                'id' => 'int',
                'pos' => 'int',
                'count' => 'int',
                'max_count' => 'int',
                'data' => 'octets',
                'proctype' => 'int',
                'expire_date' => 'int',
                'guid1' => 'int',
                'guid2' => 'int',
                'mask' => 'int',
            ],
        ]
    ]
];